feat(util): parse osmApiWay to osmWay
MapColonies/node-osm-elements pull request #20
Opened 2021-01-24 13:42 UTC by melancholiai

2021-01-24 17:01 UTC, syncush requested changes

2021-01-24 17:01 UTC, syncush commented on commitlint.config.js
> +    "scope-enum": [2, "always", ["util", "node", "way", "relation", "changeset", "osmChange", "deps", "configurations"]],
the feature is on way (`parseOsmWayApi()`) therefore the commit message does not fit.

2021-01-24 17:01 UTC, syncush commented on package.json
> +  "author": "MapColonies",
good catch

2021-01-24 17:01 UTC, syncush commented on src/util/util.ts
> +import { BaseElement, OsmNode, OsmWay, OsmApiWay, Types } from '..';
now that we have a util function I would move all the interfaces to interfaces folder with all the proper interfaces and a proper `index.ts`, then import it nicely in this `util.ts` file, our `index.ts` should be minimal at this point we have BL in our package.

2021-01-24 17:01 UTC, syncush commented on src/index.ts
> +
is it for only full api call or even not full ?

2021-01-24 17:01 UTC, syncush commented on src/index.ts
> +export { BaseElement, OsmNode, OsmWay, OsmApiWay, OsmRelation, Changeset, OsmChange, Member, Types };
exporting Types as Types is a bit problematic IMO, we should name it ElementsType or something like that, Types is too broad

2021-01-24 17:01 UTC, syncush commented on src/index.ts
>    type: 'changeset';
why have you decided not to include `changeset` in the `Types` enum? same for `osmchange`

2021-01-25 09:06 UTC, melancholiai commented on src/util/util.ts
> +import { BaseElement, OsmNode, OsmWay, OsmApiWay, Types } from '..';
done.

2021-01-25 09:07 UTC, melancholiai commented on package.json
> +  "author": "MapColonies",
eye surgery can be declared successful

2021-01-25 09:07 UTC, melancholiai commented on commitlint.config.js
> +    "scope-enum": [2, "always", ["util", "node", "way", "relation", "changeset", "osmChange", "deps", "configurations"]],
removed util, should I only rename the pr or also all commits with util in them?

2021-01-25 09:07 UTC, melancholiai commented on src/index.ts
> +
it's for all apis. in the full endpoint along with the way you get it's nodes

2021-01-25 09:07 UTC, melancholiai commented on src/index.ts
> +export { BaseElement, OsmNode, OsmWay, OsmApiWay, OsmRelation, Changeset, OsmChange, Member, Types };
will name them all under `OsmTypes`

2021-01-25 09:08 UTC, melancholiai commented on src/index.ts
>    type: 'changeset';
if I add them, it shouldn't be renamed as `ElementsType` (as mentioned in the comment above).
named them as `OsmTypes`

2021-01-25 09:42 UTC, syncush approved these changes

2021-01-25 09:49 UTC, merged